apiVersion: v1
kind: ConfigMap
metadata:
  name: faq-config
  namespace: faq-chatbot
data:
  MODEL_NAME: "gemini-2.5-flash"
  SIMILARITY_THRESHOLD: "0.75"
  PORT: "4000"
  DB_PATH: "/data/faq.db"
  AZURE_CLIENT_ID: "7dec5ac4-d4bb-469b-a57b-8f8bceacdcc9"
  AZURE_TENANT_ID: "348c3131-b1a7-4732-bda7-1157b7c25548"
