apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: faq-ingress
  namespace: faq-chatbot
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - faq.local
      secretName: faq-tls-secret
  rules:
    - host: faq.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: faq-client-svc
                port:
                  number: 80
