apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: faq-db-pvc
  namespace: faq-chatbot
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
  # Rancher Desktop (k3s) uses local-path provisioner by default
  storageClassName: local-path
